package org.furb.arbuilder.ui;

import java.io.File;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerException;

import org.furb.arbuilder.Controle;
import org.furb.arbuilder.GraficoLigacao;
import org.furb.arbuilder.GraficoOperador;
import org.furb.arbuilder.GraficoTabela;
import org.furb.arbuilder.Operadores;
import org.furb.arbuilder.PainelGrafico;
import org.furb.arbuilder.XML;
import org.furb.arbuilder.bd.DBUtil;

/**
 * 
 * @author Jonathan Hess, AndrÃ© R. Sousa
 */
public class Interface extends javax.swing.JFrame {

	private static final long serialVersionUID = -7925879363837614461L;
	private PainelGrafico painelGrafico = null;
	private Controle controle = null;
	private XML xml = null;
	private boolean arquivoAberto = false;

	/** Creates new form Interface */
	public Interface(Controle controle) {

		initComponents();
		super.setLocationRelativeTo(null);

		// PainelGrafico contem metodos para visualizacao do grafico
		this.painelGrafico = new PainelGrafico(controle, this,
				painelGraficoPai, listaTabelas);
		this.controle = controle;
		this.xml = new XML();
		this.setEditarParametrosTabela("");
	}

	public final void setEditarParametrosTabela(String nomeOperador) {
		this.nomeOperador.setText(nomeOperador);
		this.parm1Operador.setEditable(false);
		this.parm2Operador.setEditable(false);
		this.parm1Operador.setText("");
		this.parm2Operador.setText("");
	}

	public final void setEditarParametrosOperador(String nomeOperador,
			String parm1Operador, String parm2Operador, boolean agrupamento) {
		this.nomeOperador.setText(nomeOperador);
		this.parm1Operador.setEditable(true);
		this.parm2Operador.setEditable(true);
		this.parm1Operador.setText(parm1Operador);
		this.parm2Operador.setText(parm2Operador);

		if (agrupamento) {
			this.parm2Operador.setEditable(true);
		} else {
			this.parm2Operador.setEditable(false);
		}
	}

	public final void executarFuncaoControle(int funcao) {

		switch (funcao) {
		case 0:
			try {
				this.controle.getDAO().conectarBD();
				JOptionPane.showMessageDialog(this,
						"Banco de dados conectado com sucesso!", "Sucesso!",
						JOptionPane.INFORMATION_MESSAGE);
				this.btConectar.setEnabled(false);
				List<String> listaTabelasTemp = this.controle.getDAO()
						.getTabelasBD();
				((DefaultListModel) this.listaTabelas.getModel())
						.removeAllElements();
				for (int i = 0; i < listaTabelasTemp.size(); i++) {
					((DefaultListModel) this.listaTabelas.getModel())
							.addElement(listaTabelasTemp.get(i));
				}
			} catch (SQLException ex) {
				JOptionPane
						.showMessageDialog(
								this,
								"Erro ao tentar conectar-se do banco de dados.\nVerificar suas configurações de conexão",
								"Erro!", JOptionPane.ERROR_MESSAGE);
			}
			break;

		case 1:
			if (DBUtil.getInstance().isCanConnect()) {
				if (this.controle.getDAO().desconectarBD()) {
					JOptionPane.showMessageDialog(this,
							"Banco de dados desconectado com sucesso!",
							"Sucesso!", JOptionPane.INFORMATION_MESSAGE);
					this.btConectar.setEnabled(true);
					((DefaultListModel) this.listaTabelas.getModel())
							.removeAllElements();
				} else {
					JOptionPane.showMessageDialog(this,
							"Erro ao tentar desconectar-se do banco de dados!",
							"Erro!", JOptionPane.ERROR_MESSAGE);
				}
				;
			} else {
				JOptionPane.showMessageDialog(this,
						"Banco de dados já encontra-se desconectado !", "",
						JOptionPane.INFORMATION_MESSAGE);
			}
			break;
		}
	}

	public final void setSQL(String sql) {
		this.sqlResultante.setText(sql);
	}

	public final int verificaDesejaSalvar() {
		return JOptionPane
				.showConfirmDialog(this, "Deseja salvar seu projeto?");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btExecutarSQL = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sqlResultante = new javax.swing.JTextArea();
        painelGraficoPai = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btConectar = new javax.swing.JButton();
        btDesconectar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaTabelas = new javax.swing.JList(new DefaultListModel());
        btCriarLigacao = new javax.swing.JButton();
        btSelecao = new javax.swing.JButton();
        btProjecao = new javax.swing.JButton();
        btUniao = new javax.swing.JButton();
        btProdutoCartesiano = new javax.swing.JButton();
        btAgrupamento = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomeOperador = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        parm1Operador = new javax.swing.JTextField();
        parm2Operador = new javax.swing.JTextField();
        btDiferenca = new javax.swing.JButton();
        brJuncaoExterna = new javax.swing.JButton();
        btInterseccao = new javax.swing.JButton();
        btOrdenacao = new javax.swing.JButton();
        btDistinct = new javax.swing.JButton();
        btJuncaoTeta = new javax.swing.JButton();
        btJuncaoNatural = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btAbrir = new javax.swing.JMenuItem();
        btSalvar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        btSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btConfiguracaoBD = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btEquipe = new javax.swing.JMenuItem();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto Algebra Relacional - Banco de Dados II");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SQL resultante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 10))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 10));

        btExecutarSQL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/furb/arbuilder/resources/images/lightning_go.png"))); // NOI18N
        btExecutarSQL.setText("Executar SQL...");
        btExecutarSQL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btExecutarSQLMousePressed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        sqlResultante.setColumns(20);
        sqlResultante.setRows(5);
        sqlResultante.setLineWrap(true);
        jScrollPane2.setViewportView(sqlResultante);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExecutarSQL)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btExecutarSQL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        painelGraficoPai.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Painel grafico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 10))); // NOI18N
        painelGraficoPai.setFont(new java.awt.Font("Tahoma", 0, 10));
        painelGraficoPai.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Banco de dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 10))); // NOI18N

        btConectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/furb/arbuilder/resources/images/connect.png"))); // NOI18N
        btConectar.setText("Conectar...");
        btConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConectarActionPerformed(evt);
            }
        });

        btDesconectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/furb/arbuilder/resources/images/disconnect.png"))); // NOI18N
        btDesconectar.setText("Desconectar");
        btDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDesconectarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btConectar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btDesconectar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDesconectar)
                    .addComponent(btConectar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Caixa de ferramentas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 10))); // NOI18N

        listaTabelas.setFont(new java.awt.Font("Tahoma", 1, 11));
        jScrollPane1.setViewportView(listaTabelas);

        btCriarLigacao.setFont(new java.awt.Font("Tahoma", 1, 12));
        btCriarLigacao.setText("Efetuar relação");
        btCriarLigacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCriarLigacaoActionPerformed(evt);
            }
        });

        btSelecao.setBackground(new java.awt.Color(255, 255, 255));
        btSelecao.setFont(new java.awt.Font("Tahoma", 1, 11));
        btSelecao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/furb/arbuilder/resources/images/op_selecao.png"))); // NOI18N
        btSelecao.setToolTipText("Operador Seleção");
        btSelecao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btSelecaoMousePressed(evt);
            }
        });

        btProjecao.setBackground(new java.awt.Color(255, 255, 255));
        btProjecao.setFont(new java.awt.Font("Tahoma", 1, 11));
        btProjecao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/furb/arbuilder/resources/images/op_projecao.png"))); // NOI18N
        btProjecao.setToolTipText("Operador Projeção");
        btProjecao.setFocusable(false);
        btProjecao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btProjecao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btProjecao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btProjecaoMousePressed(evt);
            }
        });

        btUniao.setBackground(new java.awt.Color(255, 255, 255));
        btUniao.setFont(new java.awt.Font("Tahoma", 1, 11));
        btUniao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/furb/arbuilder/resources/images/op_uniao.png"))); // NOI18N
        btUniao.setToolTipText("Operador União");
        btUniao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btUniaoMousePressed(evt);
            }
        });

        btProdutoCartesiano.setBackground(new java.awt.Color(255, 255, 255));
        btProdutoCartesiano.setFont(new java.awt.Font("Tahoma", 1, 11));
        btProdutoCartesiano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/furb/arbuilder/resources/images/op_produto_cartesiano.png"))); // NOI18N
        btProdutoCartesiano.setToolTipText("Operador Produto Cartesiano");
        btProdutoCartesiano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btProdutoCartesianoMousePressed(evt);
            }
        });

        btAgrupamento.setBackground(new java.awt.Color(255, 255, 255));
        btAgrupamento.setFont(new java.awt.Font("Tahoma", 1, 11));
        btAgrupamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/furb/arbuilder/resources/images/op_agrupamento.png"))); // NOI18N
        btAgrupamento.setToolTipText("Operador Agrupamento");
        btAgrupamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btAgrupamentoMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Tabela(s) do banco de dados:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Operadores de algebra relacional:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Propriedades da tabela/operador:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLabel4.setText("Nome:");

        nomeOperador.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLabel5.setText("Parametro(s):");

        parm1Operador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parm1OperadorActionPerformed(evt);
            }
        });

        parm2Operador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parm2OperadorActionPerformed(evt);
            }
        });

        btDiferenca.setBackground(new java.awt.Color(255, 255, 255));
        btDiferenca.setFont(new java.awt.Font("Tahoma", 1, 11));
        btDiferenca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/furb/arbuilder/resources/images/op_diferenca.png"))); // NOI18N
        btDiferenca.setToolTipText("Operador Diferença");
        btDiferenca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btDiferencaMousePressed(evt);
            }
        });

        brJuncaoExterna.setBackground(new java.awt.Color(255, 255, 255));
        brJuncaoExterna.setFont(new java.awt.Font("Tahoma", 1, 11));
        brJuncaoExterna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/furb/arbuilder/resources/images/op_juncao.png"))); // NOI18N
        brJuncaoExterna.setToolTipText("Operacao Junção Externa");
        brJuncaoExterna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                brJuncaoExternaMousePressed(evt);
            }
        });

        btOrdenacao.setBackground(new java.awt.Color(255, 255, 255));
        btOrdenacao.setFont(new java.awt.Font("Tahoma", 1, 11));
        btOrdenacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/furb/arbuilder/resources/images/op_ordenacao.png"))); // NOI18N
        btOrdenacao.setToolTipText("Operacao Ordenação");
        btOrdenacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btOrdenacaoMousePressed(evt);
            }
        });

        btDistinct.setBackground(new java.awt.Color(255, 255, 255));
        btDistinct.setFont(new java.awt.Font("Tahoma", 1, 11));
        btDistinct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/furb/arbuilder/resources/images/op_distinct.png"))); // NOI18N
        btDistinct.setToolTipText("Operacao Distinct");
        btDistinct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btDistinctMousePressed(evt);
            }
        });
        
        btJuncaoTeta.setBackground(new java.awt.Color(255, 255, 255));
        btJuncaoTeta.setFont(new java.awt.Font("Tahoma", 1, 11));
        btJuncaoTeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/furb/arbuilder/resources/images/op_juncaoTeta.png"))); // NOI18N
        btJuncaoTeta.setToolTipText("Operacao Junção Teta");
        btJuncaoTeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
            	btJuncaoTetaMousePressed(evt);
            }
        });
        
        btJuncaoNatural.setBackground(new java.awt.Color(255, 255, 255));
        btJuncaoNatural.setFont(new java.awt.Font("Tahoma", 1, 11));
        btJuncaoNatural.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/furb/arbuilder/resources/images/op_juncaoNatural.png"))); // NOI18N
        btJuncaoNatural.setToolTipText("Operacao Junção Natural");
        btJuncaoNatural.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
            	btJuncaoNaturalMousePressed(evt);
            }
        });
        
        btInterseccao.setBackground(new java.awt.Color(255, 255, 255));
        btInterseccao.setFont(new java.awt.Font("Tahoma", 1, 11));
        btInterseccao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/furb/arbuilder/resources/images/op_juncaoNatural.png"))); // NOI18N
        btInterseccao.setToolTipText("Operacao Intersecção");
        btInterseccao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
            //	btInterseccaoMousePressed(evt);
            }
        });
        
        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btCriarLigacao)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btDiferenca, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                    .addComponent(btSelecao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(btProjecao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btUniao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(brJuncaoExterna, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btOrdenacao, 0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btDistinct, 0, 0, Short.MAX_VALUE)
                                .addComponent(btProdutoCartesiano, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btAgrupamento, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btJuncaoTeta, 0, 0, Short.MAX_VALUE))
                        
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btJuncaoNatural, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        /*.addComponent(btInterseccao, 0, 0, Short.MAX_VALUE)*/))
                        
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(nomeOperador, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(parm1Operador, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(parm2Operador, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btSelecao, 0, 0, Short.MAX_VALUE)
                    .addComponent(btProjecao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btUniao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btProdutoCartesiano, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btAgrupamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                    		.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    				 .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)                    				
                        .addComponent(btDiferenca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, Short.MAX_VALUE)
                        .addComponent(brJuncaoExterna, javax.swing.GroupLayout.Alignment.TRAILING, 0, 0, Short.MAX_VALUE))
                    .addComponent(btOrdenacao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDistinct, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(btJuncaoNatural, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                  /*.addComponent(btInterseccao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)*/)
                  
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCriarLigacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4))
                 .addComponent(btJuncaoTeta, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addComponent(btJuncaoNatural, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeOperador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parm1Operador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parm2Operador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jMenu1.setText("Arquivo");

        btAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/furb/arbuilder/resources/images/folder.png"))); // NOI18N
        btAbrir.setText("Abrir...");
        btAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btAbrirMousePressed(evt);
            }
        });
        jMenu1.add(btAbrir);

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/furb/arbuilder/resources/images/disk.png"))); // NOI18N
        btSalvar.setText("Salvar como...");
        btSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btSalvarMousePressed(evt);
            }
        });
        jMenu1.add(btSalvar);
        jMenu1.add(jSeparator1);

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/furb/arbuilder/resources/images/stop.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btSairMousePressed(evt);
            }
        });
        jMenu1.add(btSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Configurar");

        btConfiguracaoBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/furb/arbuilder/resources/images/database_gear.png"))); // NOI18N
        btConfiguracaoBD.setText("Banco de dados");
        btConfiguracaoBD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btConfiguracaoBDMousePressed(evt);
            }
        });
        jMenu2.add(btConfiguracaoBD);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Sobre");

        btEquipe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/furb/arbuilder/resources/images/group.png"))); // NOI18N
        btEquipe.setText("Equipe");
        btEquipe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btEquipeMousePressed(evt);
            }
        });
        jMenu3.add(btEquipe);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelGraficoPai, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(painelGraficoPai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void btSairMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btSairMousePressed
		int ret = this.verificaDesejaSalvar();

		if (ret != 2) {
			if (ret == 0) {
				this.btSalvarMousePressed(evt);
			}
			this.dispose();
		}
	}// GEN-LAST:event_btSairMousePressed

	private void btSelecaoMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btSelecaoMousePressed
		this.painelGrafico.setNovoOperador(0);
	}// GEN-LAST:event_btSelecaoMousePressed

	private void btProdutoCartesianoMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btProdutoCartesianoMousePressed
		this.painelGrafico.setNovoOperador(3);
	}// GEN-LAST:event_btProdutoCartesianoMousePressed

	private void btAgrupamentoMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btAgrupamentoMousePressed
		this.painelGrafico.setNovoOperador(4);
	}// GEN-LAST:event_btAgrupamentoMousePressed

	private void btProjecaoMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btProjecaoMousePressed
		this.painelGrafico.setNovoOperador(1);
	}// GEN-LAST:event_btProjecaoMousePressed

	private void btUniaoMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btUniaoMousePressed
		this.painelGrafico.setNovoOperador(2);
	}// GEN-LAST:event_btUniaoMousePressed

	private void btDiferencaMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btDiferencaMousePressed
		this.painelGrafico.setNovoOperador(5);
	}// GEN-LAST:event_btDiferencaMousePressed

	private void brJuncaoExternaMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_brJuncaoExternaMousePressed
		this.painelGrafico.setNovoOperador(7);
	}// GEN-LAST:event_brJuncaoExternaMousePressed

	private void btOrdenacaoMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btOrdenacaoMousePressed
		this.painelGrafico.setNovoOperador(6);
	}// GEN-LAST:event_btOrdenacaoMousePressed

	private void btDistinctMousePressed(java.awt.event.MouseEvent evt) {
		this.painelGrafico.setNovoOperador(8);
	}

	private void btJuncaoTetaMousePressed(java.awt.event.MouseEvent evt) {
		this.painelGrafico.setNovoOperador(9);
	}
	
	private void btJuncaoNaturalMousePressed(java.awt.event.MouseEvent evt) {
		this.painelGrafico.setNovoOperador(10);
	}

	private void btConfiguracaoBDMousePressed(java.awt.event.MouseEvent evt) {
		new InterfaceConfiguracao().setVisible(true);
	}

	private void btEquipeMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btEquipeMousePressed
		new InterfaceEquipe().setVisible(true);
	}// GEN-LAST:event_btEquipeMousePressed

	private void btConectarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btConectarActionPerformed

		if (DBUtil.getInstance().isCanConnect()) {
			executarFuncaoControle(0);
		} else {
			JOptionPane.showMessageDialog(this,
					"Existem campos não informados", "Alerta",
					JOptionPane.ERROR_MESSAGE);
		}

	}// GEN-LAST:event_btConectarActionPerformed

	private void btDesconectarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btDesconectarActionPerformed

		executarFuncaoControle(1);

	}// GEN-LAST:event_btDesconectarActionPerformed

	private void btCriarLigacaoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btCriarLigacaoActionPerformed
		this.painelGrafico.setNovaLigacao();
	}// GEN-LAST:event_btCriarLigacaoActionPerformed

	private void btAbrirMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btAbrirMousePressed

		if (arquivoAberto) {
			int ret = verificaDesejaSalvar();

			if (ret == 0) {
				btSalvarMousePressed(evt);
			}
			if (ret == 2) {
				return;
			}
		}

		JFileChooser fileChooser = new JFileChooser();
		fileChooser.setDialogTitle("Abrir arquivo XML...");
		fileChooser.setFileFilter(new FileNameExtensionFilter("Arquivos XML",
				"xml"));
		fileChooser.setVisible(true);

		int tmp = fileChooser.showOpenDialog(this);

		if (tmp != JFileChooser.APPROVE_OPTION) {
			return;
		}

		File file = fileChooser.getSelectedFile();

		this.painelGrafico.limparTela();
		xml.abrirXML(file.getAbsolutePath());

		// Carrega as informacoes de conexao do XML
		xml.getCabecalhoConfiguracao();

		if (DBUtil.getInstance().isCanConnect()) {
			executarFuncaoControle(0);
		}

		List<List<?>> elementos = xml.getModeloGrafico();

		for (int i = 0; i < elementos.get(0).size(); i++) {

			if (elementos.get(0).get(i) instanceof GraficoTabela) {
				this.painelGrafico.inserirTabelaNoGrafico(
						((GraficoTabela) elementos.get(0).get(i)).toString(),
						((GraficoTabela) elementos.get(0).get(i)).getX(),
						((GraficoTabela) elementos.get(0).get(i)).getY());
				this.painelGrafico.limparAtributo();
			}

			if (elementos.get(0).get(i) instanceof GraficoOperador) {

				int tipo = Operadores
						.getOperadorType((GraficoOperador) elementos.get(0)
								.get(i));
				this.painelGrafico.setNovoOperador(tipo);

				String parametro1 = "";
				String parametro2 = "";

				if (((GraficoOperador) elementos.get(0).get(i)).toString()
						.equals(Operadores.SELECAO.getOperador())
						|| ((GraficoOperador) elementos.get(0).get(i))
								.toString().equals(
										Operadores.PROJECAO.getOperador())
						|| ((GraficoOperador) elementos.get(0).get(i))
								.toString().equals(
										Operadores.ORDENACAO.getOperador())
						|| ((GraficoOperador) elementos.get(0).get(i))
								.toString().equals(
										Operadores.JUNCAO_EX_ESQUERDA
												.getOperador())) {
					parametro1 = ((GraficoOperador) elementos.get(0).get(i))
							.getParametro(1);
				}

				if (((GraficoOperador) elementos.get(0).get(i)).toString()
						.equals(Operadores.AGRUPAMENTO.getOperador())) {
					parametro1 = ((GraficoOperador) elementos.get(0).get(i))
							.getParametro(1);
					parametro2 = ((GraficoOperador) elementos.get(0).get(i))
							.getParametro(2);
				}

				this.painelGrafico.inserirOperadorNoGrafico(parametro1,
						parametro2, ((GraficoOperador) elementos.get(0).get(i))
								.getX(), ((GraficoOperador) elementos.get(0)
								.get(i)).getY());
				this.painelGrafico.limparAtributo();
			}
		}

		painelGrafico.refresh();

		for (int i = 0; i < elementos.get(1).size(); i++) {
			if (elementos.get(1).get(i) instanceof GraficoLigacao) {
				this.painelGrafico.inserirLigacaoNoGrafico(
						((GraficoLigacao) elementos.get(1).get(i))
								.getPosicaoPai().x, ((GraficoLigacao) elementos
								.get(1).get(i)).getPosicaoPai().y,
						((GraficoLigacao) elementos.get(1).get(i))
								.getPosicaoFilho().x,
						((GraficoLigacao) elementos.get(1).get(i))
								.getPosicaoFilho().y);
				this.painelGrafico.limparAtributo();
			}
		}

		painelGrafico.limparAtributo();
		arquivoAberto = true;

	}// GEN-LAST:event_btAbrirMousePressed

	private void parm1OperadorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_parm1OperadorActionPerformed

		painelGrafico.alterarParametroOperador(parm1Operador.getText(),
				parm2Operador.getText());

	}// GEN-LAST:event_parm1OperadorActionPerformed

	private void parm2OperadorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_parm2OperadorActionPerformed

		painelGrafico.alterarParametroOperador(parm1Operador.getText(),
				parm2Operador.getText());

	}// GEN-LAST:event_parm2OperadorActionPerformed

	private void btExecutarSQLMousePressed(java.awt.event.MouseEvent evt) {
		if (!DBUtil.getInstance().isCanConnect()) {
			JOptionPane.showMessageDialog(this,
					"Nao e possivel executar esta expressao SQL!", "Erro!",
					JOptionPane.ERROR_MESSAGE);
			return;

		} else {

			try {
				if (sqlResultante.getText().trim().isEmpty()
						|| sqlResultante.getText().contains(
								"Erro, estrutura mal-formada neste operador!")) {
					JOptionPane.showMessageDialog(this,
							"Nao e possivel executar esta expressao SQL!",
							"Erro!", JOptionPane.ERROR_MESSAGE);
				} else {
					this.controle.getDAO().executarConsultaBD(
							this.sqlResultante.getText());
				}

			} catch (Exception ex) {
				JOptionPane.showMessageDialog(this,
						"Erro durante a execucao da expressao SQL!\n\n" + ex,
						"Erro!", JOptionPane.ERROR_MESSAGE);
				return;
			}

		}
	}

	private void btSalvarMousePressed(java.awt.event.MouseEvent evt) {
		try {
			// Salva as informações de conexao em XML
			xml.setCabecalhoConfiguracao();
			xml.setModeloGrafico(this.painelGrafico);
		} catch (ParserConfigurationException ex) {
			JOptionPane.showMessageDialog(this,
					"Erro ao tentar salvar projeto!\n\n" + ex, "Erro!",
					JOptionPane.ERROR_MESSAGE);
			return;
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(this,
					"Erro ao tentar salvar projeto!\n\n" + ex, "Erro!",
					JOptionPane.ERROR_MESSAGE);
			return;
		}

		JFileChooser fileChooser = new JFileChooser();

		fileChooser.setDialogTitle("Salvar arquivo XML...");
		fileChooser.setFileFilter(new FileNameExtensionFilter("Arquivos XML",
				"xml"));
		fileChooser.setVisible(true);

		int ret = fileChooser.showSaveDialog(this);

		if (ret == JFileChooser.APPROVE_OPTION) {
			try {
				xml.salvarXML(fileChooser.getSelectedFile().getAbsolutePath());
			} catch (ParserConfigurationException ex) {
				JOptionPane.showMessageDialog(this,
						"Erro ao tentar salvar projeto!\n\n" + ex, "Erro!",
						JOptionPane.ERROR_MESSAGE);
				return;
			} catch (TransformerConfigurationException ex) {
				JOptionPane.showMessageDialog(this,
						"Erro ao tentar salvar projeto!\n\n" + ex, "Erro!",
						JOptionPane.ERROR_MESSAGE);
				return;
			} catch (TransformerException ex) {
				JOptionPane.showMessageDialog(this,
						"Erro ao tentar salvar projeto!\n\n" + ex, "Erro!",
						JOptionPane.ERROR_MESSAGE);
				return;
			} catch (FileNotFoundException ex) {
				JOptionPane.showMessageDialog(this,
						"Erro ao tentar salvar projeto!\n\n" + ex, "Erro!",
						JOptionPane.ERROR_MESSAGE);
				return;
			}
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton brJuncaoExterna;
	private javax.swing.JMenuItem btAbrir;
	private javax.swing.JButton btAgrupamento;
	private javax.swing.JButton btConectar;
	private javax.swing.JMenuItem btConfiguracaoBD;
	private javax.swing.JButton btCriarLigacao;
	private javax.swing.JButton btDesconectar;
	private javax.swing.JButton btDiferenca;
	private javax.swing.JButton btDistinct;
	private javax.swing.JButton btJuncaoTeta;
	private javax.swing.JButton btJuncaoNatural;
	private javax.swing.JButton btInterseccao;
	private javax.swing.JMenuItem btEquipe;
	private javax.swing.JButton btExecutarSQL;
	private javax.swing.JButton btOrdenacao;
	private javax.swing.JButton btProdutoCartesiano;
	private javax.swing.JButton btProjecao;
	private javax.swing.JMenuItem btSair;
	private javax.swing.JMenuItem btSalvar;
	private javax.swing.JButton btSelecao;
	private javax.swing.JButton btUniao;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JList listaTabelas;
	private javax.swing.JTextField nomeOperador;
	private javax.swing.JPanel painelGraficoPai;
	private javax.swing.JTextField parm1Operador;
	private javax.swing.JTextField parm2Operador;
	private javax.swing.JTextArea sqlResultante;
	// End of variables declaration//GEN-END:variables

}